# Generated by Django 4.2.4 on 2023-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='travel_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Travel time'),
        ),
    ]
