# Generated by Django 4.2.5 on 2023-09-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_main', '0003_rename_train_city'),
        ('wagon', '0002_airplane_travel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Route name')),
                ('travel_times', models.PositiveSmallIntegerField(default=0, verbose_name='Total travel time')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_from_city_set', to='cities_main.city', verbose_name='From city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_city_set', to='cities_main.city', verbose_name='To city')),
                ('trains', models.ManyToManyField(to='wagon.airplane', verbose_name='Airplane list')),
            ],
            options={
                'verbose_name': 'Route name',
                'verbose_name_plural': 'Routes',
                'ordering': ['name'],
            },
        ),
    ]
